// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var MainPage, ScopedRouter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ScopedRouter = require("./ScopedRouter");

  MainPage = (function(_super) {

    __extends(MainPage, _super);

    function MainPage() {
      MainPage.__super__.constructor.apply(this, arguments);
      console.log("MainPage " + this.app);
      this.bindroute("/mainpage", 'get', this.renderGet);
    }

    MainPage.prototype.renderGet = function(req, res) {
      return res.send("OK");
    };

    return MainPage;

  })(ScopedRouter);

  global.exports = module.exports = MainPage;

}).call(this);
