// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var ScopedRouter;

  ScopedRouter = (function() {

    function ScopedRouter(app) {
      this.app = app;
    }

    ScopedRouter.prototype.bindroute = function(path, method, handler) {
      var _this = this;
      return this.app[method](path, function() {
        return handler.apply(_this, arguments);
      });
    };

    return ScopedRouter;

  })();

  module.exports = ScopedRouter;

}).call(this);
